// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIgv5_Xguy-DP2SGAtvVvvGVYp462-P8E',
    appId: '1:336519368427:web:5b30d12028c7a766fe38ae',
    messagingSenderId: '336519368427',
    projectId: 'fruit-hub-d80af',
    authDomain: 'fruit-hub-d80af.firebaseapp.com',
    storageBucket: 'fruit-hub-d80af.firebasestorage.app',
    measurementId: 'G-4HRYG3R61H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uc6xT_4Tfeg6teYauXcjH6R1ZB1hIyI',
    appId: '1:336519368427:android:8f4d79050fd2cadbfe38ae',
    messagingSenderId: '336519368427',
    projectId: 'fruit-hub-d80af',
    storageBucket: 'fruit-hub-d80af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KgUIH4EYrrMNUX8-BsPzBxmY-OICb1Y',
    appId: '1:336519368427:ios:fa50564613b49e2bfe38ae',
    messagingSenderId: '336519368427',
    projectId: 'fruit-hub-d80af',
    storageBucket: 'fruit-hub-d80af.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KgUIH4EYrrMNUX8-BsPzBxmY-OICb1Y',
    appId: '1:336519368427:ios:fa50564613b49e2bfe38ae',
    messagingSenderId: '336519368427',
    projectId: 'fruit-hub-d80af',
    storageBucket: 'fruit-hub-d80af.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIgv5_Xguy-DP2SGAtvVvvGVYp462-P8E',
    appId: '1:336519368427:web:88bf5cb5a218cb51fe38ae',
    messagingSenderId: '336519368427',
    projectId: 'fruit-hub-d80af',
    authDomain: 'fruit-hub-d80af.firebaseapp.com',
    storageBucket: 'fruit-hub-d80af.firebasestorage.app',
    measurementId: 'G-0FY8NVGMNH',
  );
}
